### ISSUE TITLE
Top and bottom borders not visable

### ISSUE THREAD

**Issue by gregpawlowski** [hummal/hyper-monokai-deluxe#2]
As of 2.0.0 stable, the top and bottom borders in hyper.js are now gone for this theme. The left and right borders are still visible.

**Comment by philipp-winterle** [comment]
confirmed. Will be fixed soon

**Comment by philipp-winterle** [comment]
Load version v1.0.2 from npm. :)

**Comment by PxlBuzzard** [comment]
The top bar is rendering a bit weirdly now. Specifically:

- the top border isn't all the way on top
- the header stops about halfway through the Close button

This is on a current version of Windows 10 with no other UI changes to Hyper.

![image](https://user-images.githubusercontent.com/512416/39008843-bed699c6-43be-11e8-9806-917a23e05024.png)

**Comment by philipp-winterle** [comment]
Thank you for reporting. Missing styles added. 
Version 1.0.3 released

**Comment by gregpawlowski** [comment]
Thank you for your effort, 1.0.3 appear to work, appears to be resolved!
